### ISSUE TITLE
As a developer I want to install the project and export a database dump

### ISSUE THREAD

**Issue by asghaier** [achraf-jeday/newproj3#7]
**Hints:**
* create a database for the project
* Create and enable an apache2 vhost for the project
* Install the project using drush si
* Export the database dump using drush sql-dump

**AC:**
* when I go to the root folder of the project I should see a database dump file "dump.sql" of the installed project.

**Comment by achraf-jeday** [comment]
All finished you can test now thanks.

**Comment by asghaier** [comment]
dump.sql file tested and works correctly. Closing this ticket.
